adds hero
Alyona-Nekhryshchyniuk/Team23 pull request #12
Opened 2022-09-04 20:32 UTC by supirgigi

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk requested changes

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/hero.html
> +          <p class="hero-info-list__number">16</p>
Здесь просто цифра. Может сделать спан?

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/hero.html
> +          <p class="hero-info-list__number">16</p>
можно выделить тегом стронг

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/hero.html
> +        <img
а размеры картинки на случай если картинка не подгружается?

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +  left: -20px;
px указывать при топ, лефт, райт, боттом не надо

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +  height: 502px;
не нужно задавать фиксированную высоту секции, она должна выстаиваться сама по контенту, посмотри почему у тебя контент подпрыгивает, если убрать высоту

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +    background-image: url(../images/hero/tablet-dots.png);
Нужно добавить min-device-px-ratio 2, min-resolution 2 dppx, 192 dpi для всех bg-img @2x

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +  text-align: left;
text-align не нужен - по умолчанию и так лефт

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +    @include font(900, 46px, 1.22);
fw и lh и так наследуется, просто поставь отдельный fsize

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +    @include font(400, 24px, 0.54);
fw и lh и так наследуется, просто поставь отдельный fsize

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +  margin-bottom: 32px;
нельзя чтоб блок БЕМ влиял на своих соседей, маржин нужно давать на микс, типо .heri-info__hero-title в твоем случае

2022-09-05 08:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_hero.scss
> +  .hero-info {
нельзя чтоб блок БЕМ влиял на своих соседей, маржин нужно давать на микс

2022-09-05 15:14 UTC, supirgigi commented on src/sass/components/_hero.scss
> +  .hero-info {
исправил

2022-09-05 15:14 UTC, supirgigi commented on src/sass/components/_hero.scss
> +  margin-bottom: 32px;
исправил

2022-09-05 15:15 UTC, supirgigi commented on src/sass/components/_hero.scss
> +    @include font(400, 24px, 0.54);
исправил

2022-09-05 15:15 UTC, supirgigi commented on src/sass/components/_hero.scss
> +    @include font(900, 46px, 1.22);
исправил

2022-09-05 15:15 UTC, supirgigi commented on src/sass/components/_hero.scss
> +  text-align: left;
исправил

2022-09-05 15:16 UTC, supirgigi commented on src/sass/components/_hero.scss
> +  height: 502px;
исправил

2022-09-06 03:26 UTC, supirgigi commented
Поменял картинку мороженого на планшете (старая была обрезана немного), добавил width и height на pictures, 2х точки и их стили

2022-09-06 03:27 UTC, supirgigi commented on src/partials/hero.html
> +        <img
исправил

2022-09-06 03:27 UTC, supirgigi commented on src/sass/components/_hero.scss
> +    background-image: url(../images/hero/tablet-dots.png);
исправил

2022-09-06 07:44 UTC, Alyona-Nekhryshchyniuk approved these changes

2022-09-06 07:44 UTC, merged