adds button styles
Alyona-Nekhryshchyniuk/Team23 pull request #13
Opened 2022-09-04 20:35 UTC by supirgigi

2022-09-05 09:23 UTC, Alyona-Nekhryshchyniuk requested changes

2022-09-05 09:23 UTC, Alyona-Nekhryshchyniuk commented on src/sass/utils/_buttons.scss
> +  height: 42px;
высота не нужна - есть паддинги

2022-09-05 09:23 UTC, Alyona-Nekhryshchyniuk commented on src/sass/utils/_buttons.scss
> +  outline: transparent;
аутлайн может появится только при ховере или фокусе. По умолчанию его и так нет

2022-09-05 09:23 UTC, Alyona-Nekhryshchyniuk commented on src/sass/utils/_buttons.scss
> +  min-width: 83px;
мин-видс не нужен. Есть паддинги

2022-09-05 09:23 UTC, Alyona-Nekhryshchyniuk commented on src/sass/utils/_buttons.scss
> +    padding: 12px 32px;
Сделай паддинги для общего класса .button 12px 34 рх, другие паддинги - они будут задаваться отдельно, они скорее исключение

2022-09-05 09:23 UTC, Alyona-Nekhryshchyniuk commented on src/sass/utils/_buttons.scss
> +  @include font(600, 14px, 1.21);
вынеси миксин фонт для общего класса .button со значениями 600, 14, 1.28.  Line-height - 1.21 - это исключение и он только в некоторых местах кастомно будет даваться

2022-09-05 15:17 UTC, supirgigi commented on src/sass/utils/_buttons.scss
> +  height: 42px;
исправил

2022-09-05 15:17 UTC, supirgigi commented on src/sass/utils/_buttons.scss
> +  outline: transparent;
исправил

2022-09-05 15:18 UTC, supirgigi commented on src/sass/utils/_buttons.scss
> +  min-width: 83px;
исправил

2022-09-06 08:35 UTC, Alyona-Nekhryshchyniuk submitted a review, later dismissed

2022-09-06 08:39 UTC, Alyona-Nekhryshchyniuk submitted a review, later dismissed

2022-09-06 08:52 UTC, merged