Feature/about
Alyona-Nekhryshchyniuk/Team23 pull request #18
Opened 2022-09-04 23:19 UTC by IIIMaroIII

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk requested changes

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/utils/_directives.scss
> +  line-height: $lh / $fs;
миксин верни на исходную. Он был нормальным - работал

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +    background-image: url('../images/phone-cow.jpg');
в путях нужно будет указать название папки своей секции. Картинки твои в секции about лежат отдельно

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/partials/about.html
> +        <a href="" class="button">
Это не ссылка. это тег button, потому что он открывает модалку, а не отсылает в другую часть страницы

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +.button {
напиши Диме, договоритесь что кто-то из вас сделает стили для общего класса button, которые нужно поместить в отдельный паршал buttons.scss. Лучше наверное если это сделаешь ты, потому что у тебя уже готовы стили. Диме напиши, чтоб не было конфликтов, он занимается кнопками

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +  text-align: center;
текст-елайн не нужен. там нечего центрировать.

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +  padding-bottom: 12px;
добавь еще паддинги справа и слева 34пх. У тебя сейчас их нет потому, что у тебя там ссылка на всю ширину, а не тег button. Ссылка не нужна

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +  display: block;
В общий класс для всех кнопок не нужно выносить дисплей блок. кому-то нужен инлайн-блок

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/partials/about.html
> +    <h2 class="about__subtitle subtitle">tradition and love</h2>
Не по ТЗ. “tradition and love” – є лейблом заголовка і не виділяється тегом заголовка.
“how it’s made?” - Заголовок секції.

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/partials/about.html
> +      <div class="cow">
не нужен отдельный див для бг и отдельный для картинки. Думаю, что див с картинкой надо убрать так как это не контентное, а декоративное изображение, ты ж его позиционируешь относительно бг. Див для бг оставь и общий див убери

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/partials/about.html
> +          Read more <span class="button__symbol">&#62;</span></a
стрелка не нужна. Она уже у нас есть

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +  letter-spacing: 0.04em;
ls 0.04 у нас есть в base ко всему документу по умолчанию

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +  font-family: 'Montserrat';
ff у нас есть в base ко всему документу по умолчанию. он и так наследуется

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +      align-items: center;
он не нужен

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +    margin-bottom: 32px;
он тебе нужен только под телефон. не надо чтоб он тянулся на все устройства

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +    // @include font($fw: 400, $fs: 30px, $lh: 38px);
в миксин lh выноси не в px, а высчитав на калькуляторе десятиричное число

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +      flex-direction: row;
дирекшн и так по умолчанию ро, а колонка у тебя осталась только до 767пх

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +    margin-top: 39px;
дискрипшн у тебя БЕМ блок, он не может влиять на своих соседей, Если хочешь маржин, нужно делать микс

2022-09-05 11:03 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_about.scss
> +    margin-top: 39px;
и мне кажется это паддинг, подумай

2022-09-05 13:24 UTC, IIIMaroIII commented on src/sass/utils/_directives.scss
> +  line-height: $lh / $fs;
вернул

2022-09-05 13:25 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +    background-image: url('../images/phone-cow.jpg');
уже увидел когда начал advantages, но у меня не подтянулись почему-то эти папки в about.

2022-09-05 13:29 UTC, IIIMaroIII commented on src/partials/about.html
> +        <a href="" class="button">
ок, поменял

2022-09-05 13:45 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +.button {
done

2022-09-05 13:46 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +  text-align: center;
И как ты его заметила ))))

2022-09-05 13:48 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +  text-align: center;
done

2022-09-05 13:52 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +  padding-bottom: 12px;
done

2022-09-05 13:53 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +  display: block;
Ну так если кому нужно, то перебьют у себя. Практически всегда используется block

2022-09-05 13:56 UTC, IIIMaroIII commented on src/partials/about.html
> +    <h2 class="about__subtitle subtitle">tradition and love</h2>
согласен, тз не читал. исправил

2022-09-05 13:59 UTC, IIIMaroIII commented on src/partials/about.html
> +      <div class="cow">
это я переделаю на многослойный фон. провозился вчера очень долго, не получалось.
поэтому сделал через absolute, чтоб сверстать эту секцию.
Чуть позже исправлю, на многослойный с 1 div.

2022-09-05 13:59 UTC, IIIMaroIII commented on src/partials/about.html
> +          Read more <span class="button__symbol">&#62;</span></a
ее вчера у меня не было. так как она была кривая. как будет спрайт поменяю.

2022-09-05 14:04 UTC, IIIMaroIII commented on src/partials/about.html
> +          Read more <span class="button__symbol">&#62;</span></a
не знаю в чем дело, у меня не обновляется моя ветка about. Делал и pull в ветке main, потом переходил в свою ветку делал fetch но не меняются папки images с новым sprite.

2022-09-05 14:05 UTC, IIIMaroIII commented on src/partials/about.html
> +          Read more <span class="button__symbol">&#62;</span></a
вечером на meeting тогда может кто-то что подскажет. расшарю экран

2022-09-05 14:06 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +  letter-spacing: 0.04em;
done

2022-09-05 14:07 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +  font-family: 'Montserrat';
done

2022-09-05 14:10 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +      align-items: center;
сам не пониманию зачем он здесь. 
Убрал

2022-09-05 14:12 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +    margin-bottom: 32px;
done

2022-09-05 14:13 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +      flex-direction: row;
согласен. done

2022-09-05 14:20 UTC, IIIMaroIII commented on src/sass/components/_about.scss
> +    margin-top: 39px;
done

2022-09-06 08:16 UTC, Alyona-Nekhryshchyniuk approved these changes

2022-09-06 08:17 UTC, merged