Products
Alyona-Nekhryshchyniuk/Team23 pull request #23
Opened 2022-09-05 15:08 UTC by IvanGlog

Додано розмітку і стилі, виправлено посилання на картинки, додано бекграунди.

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk requested changes
обрати внимание, что слетают стили на телефонах меньше 480px. Вижу ты добавляешь картинки, но не вижу @2x или они уже есть в папке ?

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +            <p class="product-label">100% natural</p>
по ТЗ “100% natural” - є лейблом заголовка, тоесть нужен тег лейбл, а не р

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +            <h2 class="product-subtitle">products</h2>
почему сабтайтл? где тайтл тогда?

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +            <li class="product-item first">
Ли не может быть БЕМ блоком, она же неразрывно связана с юл. А first это наверное должен быть модификатор, а у тебя тоже отдельный БЕМ блок

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +                <h3 class="product-item__subtitle">ice cream</h3>
почему сабтайтл? где у айтема тогда тайтл?

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +                    <a href="" class="product-item__link">
это не ссылка, а кнопка с тайпом баттон, так как она открывает модалку

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +                        <svg class="product-item__arrow">
нужно указать видс и хайт в свг

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +                <div class="product-item__wrapper">
этот див, думаю, лишний

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_products.scss
> +        font-style: normal;
он по умолчанию нормаль

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_products.scss
> +        line-height: 1.23;
на телефоне и так 1.23. он наследуется сам

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_products.scss
> +        letter-spacing: 0.04em;
на весь боди навешали 0.04ем. он наследуется

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_products.scss
> +        font-family: 'Montserrat';
это семейство у нас по умолчанию

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_products.scss
> +        font-style: normal;
он и так нормаль

2022-09-05 16:31 UTC, Alyona-Nekhryshchyniuk commented on src/sass/components/_products.scss
> +    .product-item {
так как стили для айтема ты включил в медиа правило мин-видс 480пх, то на телефонах поменьше эти стили слитают

2022-09-05 18:46 UTC, IvanGlog commented on src/partials/products.html
> +            <p class="product-label">100% natural</p>
Поправив

2022-09-05 18:46 UTC, IvanGlog commented on src/partials/products.html
> +            <h2 class="product-subtitle">products</h2>
Виправив

2022-09-05 18:46 UTC, IvanGlog commented on src/partials/products.html
> +            <li class="product-item first">
Змінив назви класів

2022-09-05 18:46 UTC, IvanGlog commented on src/partials/products.html
> +                <h3 class="product-item__subtitle">ice cream</h3>
Поправив

2022-09-05 18:46 UTC, IvanGlog commented on src/partials/products.html
> +                    <a href="" class="product-item__link">
Змінив

2022-09-05 18:47 UTC, IvanGlog commented on src/sass/components/_products.scss
> +        line-height: 1.23;
+

2022-09-05 18:47 UTC, IvanGlog commented on src/sass/components/_products.scss
> +        letter-spacing: 0.04em;
Виправив

2022-09-05 18:47 UTC, IvanGlog commented on src/sass/components/_products.scss
> +        font-family: 'Montserrat';
Виправив

2022-09-05 18:47 UTC, IvanGlog commented on src/sass/components/_products.scss
> +        font-style: normal;
Забрав

2022-09-05 18:47 UTC, IvanGlog commented on src/sass/components/_products.scss
> +    .product-item {
Змінив стилі для телефона

2022-09-05 18:48 UTC, IvanGlog commented on src/partials/products.html
> +                        <svg class="product-item__arrow">
Вказано в CSS

2022-09-05 18:49 UTC, IvanGlog commented on src/partials/products.html
> +                <div class="product-item__wrapper">
Тепер використовується для вирівнювання кнопки

2022-09-05 18:49 UTC, IvanGlog commented on src/sass/components/_products.scss
> +        font-style: normal;
Забрав

2022-09-06 07:56 UTC, Alyona-Nekhryshchyniuk requested changes

2022-09-06 07:56 UTC, Alyona-Nekhryshchyniuk commented on src/partials/products.html
> +                            <use href="/src/images/newSprite.svg#icon-arrow"></use>
спрайт наш называется icons.svg

2022-09-06 09:18 UTC, Alyona-Nekhryshchyniuk approved these changes

2022-09-06 09:18 UTC, merged